#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuperFluity.Droid.Resource", IsApplication=true)]

namespace SuperFluity.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000e
			public const int common_action_bar_splitter = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int common_google_signin_btn_text_dark = 2130968599;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_dark_default = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_text_dark_disabled = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_google_signin_btn_text_dark_focused = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_dark_pressed = 2130968592;
			
			// aapt resource value: 0x7f040018
			public const int common_google_signin_btn_text_light = 2130968600;
			
			// aapt resource value: 0x7f040013
			public const int common_google_signin_btn_text_light_default = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int common_google_signin_btn_text_light_disabled = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int common_google_signin_btn_text_light_focused = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int common_google_signin_btn_text_light_pressed = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int common_plus_signin_btn_text_dark = 2130968601;
			
			// aapt resource value: 0x7f040006
			public const int common_plus_signin_btn_text_dark_default = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int common_plus_signin_btn_text_dark_disabled = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_plus_signin_btn_text_dark_focused = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_plus_signin_btn_text_dark_pressed = 2130968583;
			
			// aapt resource value: 0x7f04001a
			public const int common_plus_signin_btn_text_light = 2130968602;
			
			// aapt resource value: 0x7f04000a
			public const int common_plus_signin_btn_text_light_default = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int common_plus_signin_btn_text_light_disabled = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_plus_signin_btn_text_light_focused = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int common_plus_signin_btn_text_light_pressed = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int place_autocomplete_prediction_primary_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int place_autocomplete_prediction_primary_text_highlight = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int place_autocomplete_prediction_secondary_text = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int place_autocomplete_search_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int place_autocomplete_search_text = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int place_autocomplete_separator = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_button_padding = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int place_autocomplete_powered_by_google_height = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int place_autocomplete_powered_by_google_start = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_height = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_horizontal_margin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_prediction_primary_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int place_autocomplete_prediction_secondary_text = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_progress_horizontal_margin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_progress_size = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int place_autocomplete_separator_start = 2131034119;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blackcharcoal_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int charcoallightgrey_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_ic_googleplayservices = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_disabled = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_focused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_disabled = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_focused = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_pressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_disabled = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_focused = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_normal = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_pressed = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_accept = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_discard = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_edit = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_map = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_action_new = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_action_new_picture = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_next_item = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_overflow = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_pay = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_action_person = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_action_previous_item = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_action_remove = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_action_search = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_action_share = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_action_time = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_action_view_as_list = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_credit_card_white_24dp = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_date_range_white_48dp = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_filter_list_white_48dp = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Icon = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int icon150_150 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int icon25_25 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int icon40_40 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int lightgreywhite_background = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int places_ic_clear = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int places_ic_search = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int powered_by_google_dark = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int powered_by_google_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int red_button = 2130837576;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a00ab
			public const int addgenericofficeitem = 2131361963;
			
			// aapt resource value: 0x7f0a00a9
			public const int addnewofficespace = 2131361961;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a00a2
			public const int bookingOverflowoverflow = 2131361954;
			
			// aapt resource value: 0x7f0a00a4
			public const int bookingShowAwaitingPayment = 2131361956;
			
			// aapt resource value: 0x7f0a00a5
			public const int bookingShowCancelled = 2131361957;
			
			// aapt resource value: 0x7f0a00a3
			public const int bookingShowConfirmed = 2131361955;
			
			// aapt resource value: 0x7f0a00a6
			public const int bookingShowPastBookings = 2131361958;
			
			// aapt resource value: 0x7f0a0076
			public const int bookingbackground = 2131361910;
			
			// aapt resource value: 0x7f0a0070
			public const int btnAddOfficeItems = 2131361904;
			
			// aapt resource value: 0x7f0a0010
			public const int btnBookingCancel = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int btnBookingEdit = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int btnBookingPayment = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int btnBookingQuote = 2131361805;
			
			// aapt resource value: 0x7f0a0011
			public const int btnBookingShare = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int btnBookingViewMap = 2131361810;
			
			// aapt resource value: 0x7f0a0063
			public const int btnFridayClose = 2131361891;
			
			// aapt resource value: 0x7f0a0062
			public const int btnFridayOpen = 2131361890;
			
			// aapt resource value: 0x7f0a008a
			public const int btnListing = 2131361930;
			
			// aapt resource value: 0x7f0a00a1
			public const int btnListingSave = 2131361953;
			
			// aapt resource value: 0x7f0a0053
			public const int btnMondayClose = 2131361875;
			
			// aapt resource value: 0x7f0a0052
			public const int btnMondayOpen = 2131361874;
			
			// aapt resource value: 0x7f0a0089
			public const int btnMyBookings = 2131361929;
			
			// aapt resource value: 0x7f0a0088
			public const int btnNewBooking = 2131361928;
			
			// aapt resource value: 0x7f0a0067
			public const int btnSaturdayClose = 2131361895;
			
			// aapt resource value: 0x7f0a0066
			public const int btnSaturdayOpen = 2131361894;
			
			// aapt resource value: 0x7f0a0036
			public const int btnSaveCompanyLocation = 2131361846;
			
			// aapt resource value: 0x7f0a006c
			public const int btnSaveOfficeHours = 2131361900;
			
			// aapt resource value: 0x7f0a006f
			public const int btnSaveOfficeItems = 2131361903;
			
			// aapt resource value: 0x7f0a0035
			public const int btnSetOfficeHours = 2131361845;
			
			// aapt resource value: 0x7f0a006b
			public const int btnSundayClose = 2131361899;
			
			// aapt resource value: 0x7f0a006a
			public const int btnSundayOpen = 2131361898;
			
			// aapt resource value: 0x7f0a0056
			public const int btnTeusdayOpen = 2131361878;
			
			// aapt resource value: 0x7f0a005f
			public const int btnThursdayClose = 2131361887;
			
			// aapt resource value: 0x7f0a005e
			public const int btnThursdayOpen = 2131361886;
			
			// aapt resource value: 0x7f0a0057
			public const int btnTuesdayClose = 2131361879;
			
			// aapt resource value: 0x7f0a005b
			public const int btnWednesdayClose = 2131361883;
			
			// aapt resource value: 0x7f0a005a
			public const int btnWednesdayOpen = 2131361882;
			
			// aapt resource value: 0x7f0a002c
			public const int btn_BookOfficeSpaceBook = 2131361836;
			
			// aapt resource value: 0x7f0a004b
			public const int btn_OfficeCalendar = 2131361867;
			
			// aapt resource value: 0x7f0a009e
			public const int btn_RegisterUser = 2131361950;
			
			// aapt resource value: 0x7f0a001f
			public const int btn_bookingcustomization_cancel = 2131361823;
			
			// aapt resource value: 0x7f0a001e
			public const int btn_bookingcustomization_confirm = 2131361822;
			
			// aapt resource value: 0x7f0a0016
			public const int btn_bookingcustomization_date = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int btn_bookingcustomization_endTime = 2131361816;
			
			// aapt resource value: 0x7f0a0017
			public const int btn_bookingcustomization_startTime = 2131361815;
			
			// aapt resource value: 0x7f0a0075
			public const int btn_deletelisting = 2131361909;
			
			// aapt resource value: 0x7f0a008c
			public const int btn_deletelocation = 2131361932;
			
			// aapt resource value: 0x7f0a003e
			public const int btn_itemSave = 2131361854;
			
			// aapt resource value: 0x7f0a0087
			public const int btn_loginCancel = 2131361927;
			
			// aapt resource value: 0x7f0a0085
			public const int btn_loginLogin = 2131361925;
			
			// aapt resource value: 0x7f0a0086
			public const int btn_loginRegister = 2131361926;
			
			// aapt resource value: 0x7f0a004a
			public const int btn_officeSpaceOfficeItems = 2131361866;
			
			// aapt resource value: 0x7f0a004c
			public const int btn_officeSpaceSave = 2131361868;
			
			// aapt resource value: 0x7f0a0081
			public const int btn_viewOfficesForBooking = 2131361921;
			
			// aapt resource value: 0x7f0a0074
			public const int btn_viewlistingonmap = 2131361908;
			
			// aapt resource value: 0x7f0a008b
			public const int btn_viewofficespace = 2131361931;
			
			// aapt resource value: 0x7f0a0061
			public const int chkFriday = 2131361889;
			
			// aapt resource value: 0x7f0a0051
			public const int chkMonday = 2131361873;
			
			// aapt resource value: 0x7f0a0065
			public const int chkSaturday = 2131361893;
			
			// aapt resource value: 0x7f0a0069
			public const int chkSunday = 2131361897;
			
			// aapt resource value: 0x7f0a005d
			public const int chkThursday = 2131361885;
			
			// aapt resource value: 0x7f0a0055
			public const int chkTuesday = 2131361877;
			
			// aapt resource value: 0x7f0a0059
			public const int chkWednesday = 2131361881;
			
			// aapt resource value: 0x7f0a004d
			public const int cv_officeCalendar = 2131361869;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a00ac
			public const int editcompanylocation = 2131361964;
			
			// aapt resource value: 0x7f0a0037
			public const int editofficeitem_scrollview = 2131361847;
			
			// aapt resource value: 0x7f0a0033
			public const int etCompanyLatitude = 2131361843;
			
			// aapt resource value: 0x7f0a0032
			public const int etCompanyLocationAddress = 2131361842;
			
			// aapt resource value: 0x7f0a0030
			public const int etCompanyLocationContactNumber = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int etCompanyLocationEmail = 2131361841;
			
			// aapt resource value: 0x7f0a002f
			public const int etCompanyLocationName = 2131361839;
			
			// aapt resource value: 0x7f0a0034
			public const int etCompanyLongitude = 2131361844;
			
			// aapt resource value: 0x7f0a009f
			public const int etListingCompanyName = 2131361951;
			
			// aapt resource value: 0x7f0a009c
			public const int et_RegisterContactNumber = 2131361948;
			
			// aapt resource value: 0x7f0a009b
			public const int et_RegisterEmail = 2131361947;
			
			// aapt resource value: 0x7f0a0099
			public const int et_RegisterFirstName = 2131361945;
			
			// aapt resource value: 0x7f0a009a
			public const int et_RegisterLastName = 2131361946;
			
			// aapt resource value: 0x7f0a009d
			public const int et_RegisterPassword = 2131361949;
			
			// aapt resource value: 0x7f0a003b
			public const int et_itemDescription = 2131361851;
			
			// aapt resource value: 0x7f0a003d
			public const int et_itemFlatRate = 2131361853;
			
			// aapt resource value: 0x7f0a0039
			public const int et_itemTitle = 2131361849;
			
			// aapt resource value: 0x7f0a0083
			public const int et_loginEmail = 2131361923;
			
			// aapt resource value: 0x7f0a0084
			public const int et_loginPassword = 2131361924;
			
			// aapt resource value: 0x7f0a0047
			public const int et_officeSpaceDescription = 2131361863;
			
			// aapt resource value: 0x7f0a0044
			public const int et_officeSpaceFlatRate = 2131361860;
			
			// aapt resource value: 0x7f0a0042
			public const int et_officeSpaceMaxPeople = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int et_officeSpaceMinimumPeople = 2131361859;
			
			// aapt resource value: 0x7f0a0041
			public const int et_officeSpaceRoomSize = 2131361857;
			
			// aapt resource value: 0x7f0a0040
			public const int et_officeSpaceTitle = 2131361856;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a008f
			public const int invisibletextview = 2131361935;
			
			// aapt resource value: 0x7f0a00a0
			public const int ivListingCompanyLogo = 2131361952;
			
			// aapt resource value: 0x7f0a0049
			public const int ivOfficeSpacePic = 2131361865;
			
			// aapt resource value: 0x7f0a0082
			public const int iv_loginImage = 2131361922;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a00a7
			public const int listing_addnew = 2131361959;
			
			// aapt resource value: 0x7f0a008e
			public const int listofcompanylocations_fragment = 2131361934;
			
			// aapt resource value: 0x7f0a008d
			public const int listofcompanylocations_mapframe = 2131361933;
			
			// aapt resource value: 0x7f0a001a
			public const int ll_bookingcustomization_availableitems = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int ll_bookingcustomization_includeditems = 2131361819;
			
			// aapt resource value: 0x7f0a0015
			public const int ll_bookingcustomization_main = 2131361813;
			
			// aapt resource value: 0x7f0a001d
			public const int ll_bookingcustomization_quote = 2131361821;
			
			// aapt resource value: 0x7f0a0013
			public const int locationdetail_fragmentframe = 2131361811;
			
			// aapt resource value: 0x7f0a004f
			public const int locationdetail_hoursframe = 2131361871;
			
			// aapt resource value: 0x7f0a002d
			public const int locationdetail_mainframe = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int locationdetail_scrollview = 2131361838;
			
			// aapt resource value: 0x7f0a004e
			public const int locationdetail_scrollviewHours = 2131361870;
			
			// aapt resource value: 0x7f0a0073
			public const int lvCompanies = 2131361907;
			
			// aapt resource value: 0x7f0a0072
			public const int lvOfficeItems = 2131361906;
			
			// aapt resource value: 0x7f0a007e
			public const int lvUserBookings = 2131361918;
			
			// aapt resource value: 0x7f0a00a8
			public const int mainactivity_login = 2131361960;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0090
			public const int officespace_fragmentframe = 2131361936;
			
			// aapt resource value: 0x7f0a003f
			public const int officespace_scrollview = 2131361855;
			
			// aapt resource value: 0x7f0a0093
			public const int place_autocomplete_clear_button = 2131361939;
			
			// aapt resource value: 0x7f0a0095
			public const int place_autocomplete_powered_by_google = 2131361941;
			
			// aapt resource value: 0x7f0a0097
			public const int place_autocomplete_prediction_primary_text = 2131361943;
			
			// aapt resource value: 0x7f0a0098
			public const int place_autocomplete_prediction_secondary_text = 2131361944;
			
			// aapt resource value: 0x7f0a0096
			public const int place_autocomplete_progress = 2131361942;
			
			// aapt resource value: 0x7f0a0091
			public const int place_autocomplete_search_button = 2131361937;
			
			// aapt resource value: 0x7f0a0092
			public const int place_autocomplete_search_input = 2131361938;
			
			// aapt resource value: 0x7f0a0094
			public const int place_autocomplete_separator = 2131361940;
			
			// aapt resource value: 0x7f0a007f
			public const int rbCompanyLocationRating = 2131361919;
			
			// aapt resource value: 0x7f0a00aa
			public const int removeofficespace = 2131361962;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0014
			public const int scrollView1 = 2131361812;
			
			// aapt resource value: 0x7f0a002b
			public const int spnOfficeBooking_AvailableExtras = 2131361835;
			
			// aapt resource value: 0x7f0a002a
			public const int spnOfficeBooking_IncludedItems = 2131361834;
			
			// aapt resource value: 0x7f0a0045
			public const int spn_officeSpaceType = 2131361861;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0019
			public const int textView1 = 2131361817;
			
			// aapt resource value: 0x7f0a0021
			public const int textView2 = 2131361825;
			
			// aapt resource value: 0x7f0a001c
			public const int textView3 = 2131361820;
			
			// aapt resource value: 0x7f0a0024
			public const int textView4 = 2131361828;
			
			// aapt resource value: 0x7f0a0026
			public const int textView5 = 2131361830;
			
			// aapt resource value: 0x7f0a0028
			public const int textView6 = 2131361832;
			
			// aapt resource value: 0x7f0a0046
			public const int textView7 = 2131361862;
			
			// aapt resource value: 0x7f0a0048
			public const int textView8 = 2131361864;
			
			// aapt resource value: 0x7f0a007c
			public const int tv1 = 2131361916;
			
			// aapt resource value: 0x7f0a0023
			public const int tvBookOffice_MaximumPeople = 2131361827;
			
			// aapt resource value: 0x7f0a0025
			public const int tvBookOffice_MinimumPeople = 2131361829;
			
			// aapt resource value: 0x7f0a0027
			public const int tvBookOffice_OfficeType = 2131361831;
			
			// aapt resource value: 0x7f0a0022
			public const int tvBookOffice_Price = 2131361826;
			
			// aapt resource value: 0x7f0a0020
			public const int tvBookOffice_RoomSize = 2131361824;
			
			// aapt resource value: 0x7f0a007a
			public const int tvBooking_Date = 2131361914;
			
			// aapt resource value: 0x7f0a0079
			public const int tvBooking_Location = 2131361913;
			
			// aapt resource value: 0x7f0a0077
			public const int tvBooking_Office = 2131361911;
			
			// aapt resource value: 0x7f0a0078
			public const int tvBooking_Price = 2131361912;
			
			// aapt resource value: 0x7f0a007d
			public const int tvBooking_Status = 2131361917;
			
			// aapt resource value: 0x7f0a007b
			public const int tvBooking_Time = 2131361915;
			
			// aapt resource value: 0x7f0a0080
			public const int tvCompanyLocation_NumberOfOffices = 2131361920;
			
			// aapt resource value: 0x7f0a0071
			public const int tvExistingOfficeItems = 2131361905;
			
			// aapt resource value: 0x7f0a0060
			public const int tvFriday = 2131361888;
			
			// aapt resource value: 0x7f0a003a
			public const int tvItemDescription = 2131361850;
			
			// aapt resource value: 0x7f0a0038
			public const int tvItemTitle = 2131361848;
			
			// aapt resource value: 0x7f0a0050
			public const int tvMonday = 2131361872;
			
			// aapt resource value: 0x7f0a0029
			public const int tvOfficeBooking_Description = 2131361833;
			
			// aapt resource value: 0x7f0a006d
			public const int tvOfficeItems = 2131361901;
			
			// aapt resource value: 0x7f0a006e
			public const int tvOfficeItemsDescription = 2131361902;
			
			// aapt resource value: 0x7f0a0064
			public const int tvSaturday = 2131361892;
			
			// aapt resource value: 0x7f0a0068
			public const int tvSunday = 2131361896;
			
			// aapt resource value: 0x7f0a005c
			public const int tvThursday = 2131361884;
			
			// aapt resource value: 0x7f0a0054
			public const int tvTuesday = 2131361876;
			
			// aapt resource value: 0x7f0a0058
			public const int tvWednesday = 2131361880;
			
			// aapt resource value: 0x7f0a003c
			public const int tv_itemflatRate = 2131361852;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bookings_menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CompanyLocationDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_booking_customization = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_BookOfficeSpace = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_CompanyLocationDetail = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_EditOfficeItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_EditOfficeSpace = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment_OfficeCalendar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Fragment_OfficeHours = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Fragment_OfficeItems = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Listing = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int listings_menu = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int listItem_Booking = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ListOfUserBookings = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int locationSelectedForBooking = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Login = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Main = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int maplisting_menu = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int MapOfCompanyLocations = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int OfficeSpace = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int place_autocomplete_fragment = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int place_autocomplete_item_powered_by_google = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int place_autocomplete_item_prediction = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int place_autocomplete_progress = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Register = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int RegisterListing = 2130903065;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu_booking = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int menu_listing = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int menu_mainactivity = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int menu_officespace = 2131296259;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060022
			public const int app_name = 2131099682;
			
			// aapt resource value: 0x7f060003
			public const int auth_google_play_services_client_facebook_display_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int auth_google_play_services_client_google_display_name = 2131099650;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_api_unavailable_text = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_enable_button = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_enable_text = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_enable_title = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_install_button = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_text_phone = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_install_text_tablet = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_invalid_account_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_invalid_account_title = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_network_error_text = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_network_error_title = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_notification_ticker = 2131099653;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_restricted_profile_text = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int common_google_play_services_restricted_profile_title = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_sign_in_failed_text = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_sign_in_failed_title = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_unknown_issue = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_unsupported_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_unsupported_title = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_update_button = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_update_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_update_title = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_updating_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_updating_title = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_wear_update_text = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int common_open_on_phone = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int common_signin_button_text = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int common_signin_button_text_long = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int google_maps_key = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int hello = 2131099681;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_clear_button = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_search_hint = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int button_text = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
